"""Analysis router — DeepSeek API powered match analysis generation.

POST /api/analysis/generate
  Accepts match_id + optional extra_context, returns a 400-word Chinese
  analysis report generated by DeepSeek V4 Pro.
"""
from __future__ import annotations

import asyncio
import json
import os
import sqlite3
from datetime import datetime, timezone
from typing import Any

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from app.config import get_settings

router = APIRouter(prefix="/analysis", tags=["analysis"])

DB_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data",
    "local_stage2.db",
)

ANALYSIS_SYSTEM_PROMPT = """你是一位专业的足球分析师。你的任务是根据提供的比赛数据、模型预测和历史战绩，撰写深度赛前分析报告。

规则：
- 语气专业，像分析师而不是赌徒
- 用具体数字说话，不要空泛描述
- 不要提任何博彩平台或赔率
- 如果数据不足（冷启动球队），明确说明置信度较低
- 中文输出，约400字"""


class AnalysisRequest(BaseModel):
    match_id: str
    extra_context: str = Field(default="", description="用户手动输入的补充情报（伤停/新闻等）")


class AnalysisResponse(BaseModel):
    match_id: str
    analysis: str
    generated_at: str


def _read_match_data(clean_id: str) -> dict[str, Any] | None:
    """Read match + prediction + recent form from SQLite (sync, called via asyncio.to_thread)."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    try:
        match = conn.execute(
            """SELECT m.*, ht.name AS home_name, at.name AS away_name
               FROM matches m
               JOIN teams ht ON m.home_team_id = ht.id
               JOIN teams at ON m.away_team_id = at.id
               WHERE m.id = ?""",
            (clean_id,),
        ).fetchone()

        if not match:
            return None

        pred = conn.execute(
            """SELECT * FROM prediction_runs
               WHERE match_id = ?
               ORDER BY created_at DESC LIMIT 1""",
            (clean_id,),
        ).fetchone()

        home_name = match["home_name"]
        away_name = match["away_name"]
        match_date = match["match_date"]

        def get_recent_form(team_name: str, before_date: str) -> list[str]:
            rows = conn.execute(
                """SELECT ht.name AS home_name, at.name AS away_name,
                          m.match_date, m.competition,
                          r.home_goals, r.away_goals
                   FROM matches m
                   JOIN match_results r ON m.id = r.match_id
                   JOIN teams ht ON m.home_team_id = ht.id
                   JOIN teams at ON m.away_team_id = at.id
                   WHERE (ht.name = ? OR at.name = ?)
                     AND m.match_date < ?
                     AND m.status = 'finished'
                   ORDER BY m.match_date DESC
                   LIMIT 5""",
                (team_name, team_name, before_date),
            ).fetchall()

            form_lines = []
            for r in rows:
                if r["home_name"] == team_name:
                    result = "W" if r["home_goals"] > r["away_goals"] else ("D" if r["home_goals"] == r["away_goals"] else "L")
                    form_lines.append(f"  {r['match_date'][:10]} {result} {r['home_goals']}-{r['away_goals']} vs {r['away_name']} ({r['competition']})")
                else:
                    result = "W" if r["away_goals"] > r["home_goals"] else ("D" if r["home_goals"] == r["away_goals"] else "L")
                    form_lines.append(f"  {r['match_date'][:10]} {result} {r['away_goals']}-{r['home_goals']} vs {r['home_name']} ({r['competition']})")
            return form_lines

        home_form = get_recent_form(home_name, match_date)
        away_form = get_recent_form(away_name, match_date)

        return {
            "home_name": home_name,
            "away_name": away_name,
            "match_date": match_date,
            "competition": match["competition"],
            "is_neutral_venue": match["is_neutral_venue"],
            "prediction": pred,
            "home_form": home_form,
            "away_form": away_form,
        }
    finally:
        conn.close()


@router.post("/generate", response_model=AnalysisResponse)
async def generate_analysis(req: AnalysisRequest):
    settings = get_settings()
    deepseek_key = settings.llm_api_key or os.getenv("LLM_API_KEY", "")
    _base = (settings.llm_base_url or "https://api.deepseek.com").rstrip("/")
    deepseek_base = f"{_base}/v1"
    deepseek_model = settings.llm_model or os.getenv("LLM_MODEL", "deepseek-v4-pro")

    if not deepseek_key:
        raise HTTPException(status_code=500, detail="LLM_API_KEY 未配置，请在 .env.local 中设置")

    # Normalize match_id: strip dashes (snapshot uses dashes, DB stores without)
    clean_id = req.match_id.replace("-", "")

    # ── Read match & prediction data (offloaded to thread to avoid blocking) ─
    match_data = await asyncio.to_thread(_read_match_data, clean_id)

    if match_data is None:
        raise HTTPException(status_code=404, detail="比赛不存在")

    home_name = match_data["home_name"]
    away_name = match_data["away_name"]
    match_date = match_data["match_date"]
    pred = match_data["prediction"]
    home_form = match_data["home_form"]
    away_form = match_data["away_form"]

    # ── Build prompt ─────────────────────────────────────────
    if pred:
        prediction_section = f"""数学模型预测结果：
- 主场胜率：{pred['home_win_prob']:.1%}
- 平局概率：{pred['draw_prob']:.1%}
- 客场胜率：{pred['away_win_prob']:.1%}
- 主队预期进球(xG)：{pred['home_xg']:.2f}
- 客队预期进球(xG)：{pred['away_xg']:.2f}
- 模型版本：{pred['model_version']}
- 置信度：{pred['confidence_score']:.0%}"""
    else:
        prediction_section = "（暂无模型预测数据）"

    home_form_str = "\n".join(home_form) if home_form else "  暂无数据"
    away_form_str = "\n".join(away_form) if away_form else "  暂无数据"

    form_section = f"""{home_name} 近期战绩：
{home_form_str}

{away_name} 近期战绩：
{away_form_str}"""

    extra_section = f"\n补充情报（用户提供）：\n{req.extra_context}" if req.extra_context else ""

    user_prompt = f"""请根据以下数据，为即将进行的比赛撰写一篇深度赛前分析报告。

比赛信息：
- 主队：{home_name}
- 客队：{away_name}
- 比赛时间：{match_date[:16]}
- 赛事：{match_data['competition']}
- 场地：{'中立场' if match_data['is_neutral_venue'] else '主场优势'}

{prediction_section}

{form_section}
{extra_section}

请撰写400字左右的分析报告，结构如下：
1. **核心判断**（2-3句话，直接给出预测结论和最重要依据）
2. **数据支撑**（解读模型数据，结合近期战绩分析双方状态）
3. **关键因素**（影响这场比赛最重要的2-3个因素）
4. **风险提示**（哪些因素可能让预测失准）
5. **比赛走势**（最可能的比赛节奏和比分范围）"""

    # ── Call DeepSeek API ────────────────────────────────────
    async with httpx.AsyncClient(timeout=60.0) as client:
        try:
            response = await client.post(
                f"{deepseek_base}/chat/completions",
                headers={
                    "Authorization": f"Bearer {deepseek_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": deepseek_model,
                    "messages": [
                        {"role": "system", "content": ANALYSIS_SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    "max_tokens": 1024,
                    "temperature": 0.7,
                },
            )
            response.raise_for_status()
            data = response.json()

        except httpx.HTTPError as exc:
            raise HTTPException(status_code=502, detail=f"DeepSeek API 调用失败: {exc}")

    analysis_text = data["choices"][0]["message"]["content"]

    return AnalysisResponse(
        match_id=req.match_id,
        analysis=analysis_text,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )
