"""initial_schema

Revision ID: 2cd562a353a5
Revises: 
Create Date: 2026-04-21 00:58:50.213692
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2cd562a353a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('pipeline', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_runs'))
    )
    op.create_table('news_articles',
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles')),
    sa.UniqueConstraint('external_id', name=op.f('uq_news_articles_external_id'))
    )
    op.create_table('source_registry',
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_registry')),
    sa.UniqueConstraint('domain', name=op.f('uq_source_registry_domain'))
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=True),
    sa.Column('fifa_code', sa.String(length=3), nullable=True),
    sa.Column('confederation', sa.String(length=10), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('fifa_code', name=op.f('uq_teams_fifa_code'))
    )
    op.create_table('matches',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('home_team_id', sa.Uuid(), nullable=False),
    sa.Column('away_team_id', sa.Uuid(), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('competition', sa.String(length=50), nullable=False),
    sa.Column('competition_weight', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('is_neutral_venue', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('external_id', name=op.f('uq_matches_external_id'))
    )
    op.create_index('ix_matches_match_date_status', 'matches', ['match_date', 'status'], unique=False)
    op.create_table('players',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('is_key_player', sa.Boolean(), nullable=False),
    sa.Column('current_club', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('team_aliases',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('alias_normalized', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_aliases_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_aliases'))
    )
    op.create_index('ix_team_aliases_alias_normalized', 'team_aliases', ['alias_normalized'], unique=True)
    op.create_table('match_results',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_results_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_results')),
    sa.UniqueConstraint('match_id', name=op.f('uq_match_results_match_id'))
    )
    op.create_table('news_signals',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('impact_direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('key_players', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary_zh', sa.String(length=200), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enters_model', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name=op.f('fk_news_signals_article_id_news_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_news_signals_match_id_matches')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_news_signals_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_signals'))
    )
    op.create_index('ix_news_signals_review_status_created_at', 'news_signals', ['review_status', 'created_at'], unique=False)
    op.create_table('prediction_runs',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=False),
    sa.Column('away_xg', sa.Float(), nullable=False),
    sa.Column('score_matrix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('top3_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_feature_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('approved_signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_prediction_runs_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_runs'))
    )
    op.create_index('ix_prediction_runs_match_created', 'prediction_runs', ['match_id', 'created_at'], unique=False)
    op.create_table('content_articles',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_run_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('article_version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('correction_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_content_articles_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], name=op.f('fk_content_articles_prediction_run_id_prediction_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_articles'))
    )
    op.create_table('postmatch_eval',
    sa.Column('prediction_run_id', sa.Uuid(), nullable=False),
    sa.Column('actual_home_goals', sa.Integer(), nullable=False),
    sa.Column('actual_away_goals', sa.Integer(), nullable=False),
    sa.Column('actual_result', sa.String(length=5), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=False),
    sa.Column('exact_score_hit', sa.Boolean(), nullable=False),
    sa.Column('top3_hit', sa.Boolean(), nullable=False),
    sa.Column('calibration_bucket', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], name=op.f('fk_postmatch_eval_prediction_run_id_prediction_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postmatch_eval'))
    )
    op.create_table('postmatch_signal_eval',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_run_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_postmatch_signal_eval_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], name=op.f('fk_postmatch_signal_eval_prediction_run_id_prediction_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['news_signals.id'], name=op.f('fk_postmatch_signal_eval_signal_id_news_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postmatch_signal_eval'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postmatch_signal_eval')
    op.drop_table('postmatch_eval')
    op.drop_table('content_articles')
    op.drop_index('ix_prediction_runs_match_created', table_name='prediction_runs')
    op.drop_table('prediction_runs')
    op.drop_index('ix_news_signals_review_status_created_at', table_name='news_signals')
    op.drop_table('news_signals')
    op.drop_table('match_results')
    op.drop_index('ix_team_aliases_alias_normalized', table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_table('players')
    op.drop_index('ix_matches_match_date_status', table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('source_registry')
    op.drop_table('news_articles')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
