import type {
  AccuracyStats,
  AdminDashboardSummary,
  FeedbackItem,
  HermesDigestResponse,
  MatchCard,
  PaginatedFeedbackResponse,
  PendingArticleItem,
  PaginatedResponse,
  PendingSignalItem,
  PredictionHistoryItem,
  PredictionSnapshot,
  RecentPredictionItem,
  ReviewSummary,
  ScheduleResponse,
} from "./types";

export const mockMatches: MatchCard[] = [
  {
    id: "arg-fr",
    match_date: "2026-06-12T19:00:00Z",
    competition: "FIFA World Cup 2026",
    competition_type: "national",
    competition_code: "WC",
    competition_name_zh: "世界杯",
    stage: "Group Stage",
    status: "scheduled",
    home_team: { id: "arg", name: "Argentina", name_zh: "阿根廷", fifa_code: "ARG" },
    away_team: { id: "fra", name: "France", name_zh: "法国", fifa_code: "FRA" },
    latest_prediction: {
      latest_run_id: "run-arg-fr-1",
      home_win_prob: 0.38,
      draw_prob: 0.29,
      away_win_prob: 0.33,
      confidence_score: 0.71,
      run_type: "t_minus_24h",
    },
  },
  {
    id: "bra-esp",
    match_date: "2026-06-13T23:00:00Z",
    competition: "FIFA World Cup 2026",
    competition_type: "national",
    competition_code: "WC",
    competition_name_zh: "世界杯",
    stage: "Group Stage",
    status: "scheduled",
    home_team: { id: "bra", name: "Brazil", name_zh: "巴西", fifa_code: "BRA" },
    away_team: { id: "esp", name: "Spain", name_zh: "西班牙", fifa_code: "ESP" },
    latest_prediction: {
      latest_run_id: "run-bra-esp-1",
      home_win_prob: 0.35,
      draw_prob: 0.28,
      away_win_prob: 0.37,
      confidence_score: 0.69,
      run_type: "t_minus_24h",
    },
  },
  {
    id: "eng-jpn",
    match_date: "2026-06-14T16:00:00Z",
    competition: "FIFA World Cup 2026",
    competition_type: "national",
    competition_code: "WC",
    competition_name_zh: "世界杯",
    stage: "Group Stage",
    status: "scheduled",
    home_team: { id: "eng", name: "England", name_zh: "英格兰", fifa_code: "ENG" },
    away_team: { id: "jpn", name: "Japan", name_zh: "日本", fifa_code: "JPN" },
    latest_prediction: {
      latest_run_id: "run-eng-jpn-1",
      home_win_prob: 0.47,
      draw_prob: 0.27,
      away_win_prob: 0.26,
      confidence_score: 0.76,
      run_type: "t_minus_24h",
    },
  },
];

export const mockScheduleMatches: MatchCard[] = [
  ...mockMatches,
  {
    id: "usa-mex",
    match_date: "2026-06-18T02:00:00Z",
    competition: "FIFA World Cup 2026",
    competition_type: "national",
    competition_code: "WC",
    competition_name_zh: "世界杯",
    stage: "Group Stage - Matchday 2",
    status: "scheduled",
    home_team: { id: "usa", name: "United States", name_zh: "美国", fifa_code: "USA" },
    away_team: { id: "mex", name: "Mexico", name_zh: "墨西哥", fifa_code: "MEX" },
    latest_prediction: null,
  },
  {
    id: "ger-por",
    match_date: "2026-06-28T19:00:00Z",
    competition: "FIFA World Cup 2026",
    competition_type: "national",
    competition_code: "WC",
    competition_name_zh: "世界杯",
    stage: "Round of 32",
    status: "scheduled",
    home_team: { id: "ger", name: "Germany", name_zh: "德国", fifa_code: "GER" },
    away_team: { id: "por", name: "Portugal", name_zh: "葡萄牙", fifa_code: "POR" },
    latest_prediction: {
      latest_run_id: "run-ger-por-1",
      home_win_prob: 0.34,
      draw_prob: 0.3,
      away_win_prob: 0.36,
      confidence_score: 0.66,
      run_type: "t_minus_24h",
    },
  },
];

export const mockLatestPrediction: Record<string, PredictionSnapshot> = {
  "arg-fr": {
    id: "run-arg-fr-2",
    match_id: "arg-fr",
    run_type: "t_minus_3h",
    model_version: "dc_v1",
    as_of_time: "2026-06-12T16:00:00Z",
    created_at: "2026-06-12T16:01:00Z",
    home_win_prob: 0.4,
    draw_prob: 0.28,
    away_win_prob: 0.32,
    home_xg: 1.52,
    away_xg: 1.31,
    score_matrix: [
      [0.08, 0.09, 0.05],
      [0.12, 0.13, 0.09],
      [0.08, 0.1, 0.07],
    ],
    top3_scores: [
      { score: "1:1", prob: 0.13 },
      { score: "1:0", prob: 0.12 },
      { score: "2:1", prob: 0.1 },
    ],
    confidence_score: 0.74,
    risk_tags: ["首发不确定", "旅行疲劳"],
    approved_signals: [
      {
        id: "signal-1",
        signal_type: "lineup_hint",
        impact_direction: "uncertain",
        summary_zh: "阿根廷右路首发仍在观察",
        source_reliability: 0.82,
        confidence: 0.56,
        key_players: ["Molina"],
      },
      {
        id: "signal-2",
        signal_type: "travel",
        impact_direction: "negative",
        summary_zh: "法国转场行程偏长",
        source_reliability: 0.77,
        confidence: 0.68,
        key_players: [],
      },
    ],
    input_feature_snapshot: {
      training_rows: 128,
      match_context: { stage: "group", matchday: 1 },
    },
    article_title: "赛前预测：阿根廷 vs 法国",
    article_body:
      "结论段：模型仍略微偏向阿根廷，但差距不大，比赛更像是一场高强度的均衡对抗。支撑论据：阿根廷的进攻输出略高于法国，且中前场转换效率更稳定。风险提示：当前首发与旅途信息仍有扰动，短时间内会影响最终置信度。更新说明：这是一版 T-3h 快照，如首发确认后出现重大变化，应重新触发预测。",
    article_status: "ready",
  },
};

export const mockHistory: Record<string, PredictionHistoryItem[]> = {
  "arg-fr": [
    {
      id: "run-arg-fr-1",
      run_type: "t_minus_24h",
      as_of_time: "2026-06-11T19:00:00Z",
      created_at: "2026-06-11T19:05:00Z",
      home_win_prob: 0.38,
      draw_prob: 0.29,
      away_win_prob: 0.33,
      home_xg: 1.46,
      away_xg: 1.34,
      confidence_score: 0.71,
      risk_tags: ["旅行疲劳"],
    },
    {
      id: "run-arg-fr-2",
      run_type: "t_minus_3h",
      as_of_time: "2026-06-12T16:00:00Z",
      created_at: "2026-06-12T16:01:00Z",
      home_win_prob: 0.4,
      draw_prob: 0.28,
      away_win_prob: 0.32,
      home_xg: 1.52,
      away_xg: 1.31,
      confidence_score: 0.74,
      risk_tags: ["首发不确定", "旅行疲劳"],
    },
  ],
};

export const mockReview: ReviewSummary = {
  match_id: "arg-fr",
  actual_score: "2:1",
  actual_result: "H",
  runs: [
    {
      prediction_run_id: "run-arg-fr-1",
      run_type: "t_minus_24h",
      created_at: "2026-06-11T19:05:00Z",
      predicted_top_score: "1:1",
      actual_score: "2:1",
      brier_score: 0.18,
      log_loss: 0.95,
      exact_score_hit: false,
      top3_hit: true,
    },
    {
      prediction_run_id: "run-arg-fr-2",
      run_type: "t_minus_3h",
      created_at: "2026-06-12T16:01:00Z",
      predicted_top_score: "2:1",
      actual_score: "2:1",
      brier_score: 0.14,
      log_loss: 0.81,
      exact_score_hit: true,
      top3_hit: true,
    },
  ],
  signal_reviews: [
    {
      signal_id: "signal-1",
      summary_zh: "阿根廷右路首发仍在观察",
      signal_type: "lineup_hint",
      verdict: "neutral",
      notes: "首发变化有限，对赛果影响中性。",
    },
    {
      signal_id: "signal-2",
      summary_zh: "法国转场行程偏长",
      signal_type: "travel",
      verdict: "accurate",
      notes: "法国下半场压迫效率下降，旅行负荷判断基本成立。",
    },
  ],
};

export const mockPendingSignals: PaginatedResponse<PendingSignalItem> = {
  items: [
    {
      id: "pending-1",
      article_id: "article-1",
      match_id: "bra-esp",
      team_id: "bra",
      signal_type: "injury",
      impact_direction: "negative",
      confidence: 0.81,
      summary_zh: "巴西中卫训练强度受限",
      source_reliability: 0.82,
      key_players: ["Marquinhos"],
      created_at: "2026-06-13T08:20:00Z",
      article_title: "Brazil defender misses full training",
      source_name: "ESPN",
    },
    {
      id: "pending-2",
      article_id: "article-2",
      match_id: "eng-jpn",
      team_id: "jpn",
      signal_type: "travel",
      impact_direction: "negative",
      confidence: 0.67,
      summary_zh: "日本转场后恢复时间偏短",
      source_reliability: 0.76,
      key_players: [],
      created_at: "2026-06-13T09:10:00Z",
      article_title: "Japan schedule raises fatigue concern",
      source_name: "BBC Sport",
    },
  ],
  pagination: {
    page: 1,
    page_size: 20,
    total: 2,
  },
};

export const mockPendingArticles: PendingArticleItem[] = [
  {
    id: "content-1",
    match_id: "bra-esp",
    prediction_run_id: "run-bra-esp-1",
    title: "赛前预测：巴西 vs 西班牙",
    body:
      "结论段：这是一场极接近的比赛，西班牙在控场细节上略占优势。支撑论据：两队的 xG 预期接近，但西班牙在中场回收后的持续压制能力更稳定。风险提示：巴西后防训练状态需要进一步确认。更新说明：若赛前确认首发中卫缺阵，模型应再次更新。",
    article_version: 1,
    created_at: "2026-06-13T10:30:00Z",
  },
];

export const mockScheduleResponse: ScheduleResponse = {
  groups: [{ date: "2026-06-11", date_label: "今天", matches: mockScheduleMatches }],
  total: mockScheduleMatches.length,
  total_pages: 1,
  current_page: 1,
};

export const mockDashboard: AdminDashboardSummary = {
  new_articles_today: 14,
  pending_signals: 6,
  prediction_runs_today: 9,
  recent_5_matches_avg_brier_score: 0.163,
  last_7_days_avg_brier_score: 0.178,
  total_predictions_made: 284,
  top3_hit_rate_overall: 0.56,
  recent_accuracy: [
    {
      prediction_run_id: "run-arg-fr-2",
      match_id: "arg-fr",
      brier_score: 0.14,
      log_loss: 0.81,
      top3_hit: true,
    },
    {
      prediction_run_id: "run-eng-jpn-2",
      match_id: "eng-jpn",
      brier_score: 0.17,
      log_loss: 0.92,
      top3_hit: false,
    },
  ],
  competition_breakdown: {
    club: { match_count: 420, prediction_count: 58 },
    national: { match_count: 180, prediction_count: 15 },
    cup: { match_count: 32, prediction_count: 6 },
  },
  calibrator_status: {
    is_fitted: true,
    training_samples: 31,
    fitted_at: "2026-04-21T12:00:00Z",
    expected_calibration_error: 0.041,
  },
  beat_tasks_last_run: {
    sync_matches: "2026-04-21T04:00:00Z",
    sync_league_upcoming: "2026-04-21T05:30:00Z",
    news_ingest: "2026-04-21T12:00:00Z",
    prediction_trigger: "2026-04-21T11:30:00Z",
    postmatch_eval: "2026-04-21T06:00:00Z",
    retrain_calibrator: "2026-04-21T02:00:00Z",
    embed_articles: "2026-04-21T00:30:00Z",
  },
  recent_prediction_counts_7d: [
    { competition: "Premier League", competition_zh: "英超", prediction_count: 12 },
    { competition: "Primera Division", competition_zh: "西甲", prediction_count: 8 },
    { competition: "FIFA World Cup 2026", competition_zh: "世界杯", prediction_count: 4 },
  ],
};

export const mockHermesDigest: HermesDigestResponse = {
  generated_at: "2026-04-21T12:30:00Z",
  attention_level: "watch",
  summary: "待审信号 6 条，冲突组 2 组，待发布文章 3 篇，24 小时内比赛 2 场。",
  counts: {
    pending_signals: 6,
    conflict_groups: 2,
    pending_articles: 3,
    upcoming_matches_24h: 2,
    prediction_runs_today: 9,
  },
  focus_items: [
    { label: "信号审核", detail: "6 条待审，2 组冲突", tone: "warning" },
    { label: "文章队列", detail: "3 篇未发布分析稿", tone: "warning" },
    { label: "24h 赛程", detail: "未来 24 小时 2 场比赛", tone: "neutral" },
    { label: "校准状态", detail: "样本 31，ECE 0.041", tone: "good" },
  ],
  watch_items: [
    { label: "news_ingest", detail: "2026-04-21T12:00:00Z", tone: "urgent" },
    { label: "prediction_trigger", detail: "2026-04-21T11:30:00Z", tone: "urgent" },
  ],
  stale_tasks: [
    { name: "sync_matches", last_run: "2026-04-21T04:00:00Z", age_minutes: 510, stale: false },
    { name: "sync_league_upcoming", last_run: "2026-04-21T05:30:00Z", age_minutes: 420, stale: false },
    { name: "news_ingest", last_run: "2026-04-21T12:00:00Z", age_minutes: 30, stale: false },
    { name: "prediction_trigger", last_run: "2026-04-21T11:30:00Z", age_minutes: 60, stale: true },
    { name: "postmatch_eval", last_run: "2026-04-21T06:00:00Z", age_minutes: 390, stale: false },
    { name: "retrain_calibrator", last_run: "2026-04-21T02:00:00Z", age_minutes: 630, stale: false },
    { name: "embed_articles", last_run: "2026-04-21T00:30:00Z", age_minutes: 720, stale: true },
  ],
  calibrator_status: {
    is_fitted: true,
    training_samples: 31,
    fitted_at: "2026-04-21T12:00:00Z",
    expected_calibration_error: 0.041,
  },
};

export const mockFeedback: PaginatedFeedbackResponse = {
  items: [
    {
      id: "feedback-1",
      match_id: "arg-fr",
      article_id: null,
      feedback_type: "wrong_signal",
      description: "法国旅途疲劳的影响看起来被高估了。",
      contact: "user@example.com",
      status: "open",
      created_at: "2026-06-12T18:10:00Z",
    },
    {
      id: "feedback-2",
      match_id: "bra-esp",
      article_id: "content-1",
      feedback_type: "error_in_article",
      description: "文章里把巴西的训练信息写反了。",
      contact: null,
      status: "open",
      created_at: "2026-06-13T11:05:00Z",
    },
  ],
  pagination: {
    page: 1,
    page_size: 20,
    total: 2,
  },
};

export const mockAccuracyStats: AccuracyStats = {
  overall: {
    total_predictions: 85,
    brier_score_avg: 0.218,
    top3_hit_rate: 0.41,
    log_loss_avg: 0.982,
    last_updated: "2026-04-21T12:00:00Z",
  },
  by_competition: [
    {
      competition: "Premier League",
      competition_zh: "英超",
      total: 20,
      brier_score: 0.201,
      top3_hit_rate: 0.45,
    },
    {
      competition: "FIFA World Cup 2026",
      competition_zh: "世界杯",
      total: 12,
      brier_score: 0.234,
      top3_hit_rate: 0.38,
    },
  ],
  recent_30: {
    brier_score: 0.195,
    top3_hit_rate: 0.47,
    trend: "improving",
  },
  calibration_applied: true,
  model_version: "dc_v1",
};

export const mockRecentPredictions: RecentPredictionItem[] = [
  {
    match_id: "arg-fr",
    match_date: "2026-04-20T19:00:00Z",
    home_team_zh: "曼城",
    away_team_zh: "阿森纳",
    competition: "Premier League",
    competition_zh: "英超",
    predicted_home_win: 0.52,
    predicted_draw: 0.24,
    predicted_away_win: 0.24,
    top1_score: "2:1",
    actual_home_goals: 2,
    actual_away_goals: 1,
    result: "home_win",
    prediction_correct: true,
    top3_hit: true,
    brier_score: 0.19,
  },
  {
    match_id: "bra-esp",
    match_date: "2026-04-19T19:00:00Z",
    home_team_zh: "皇家马德里",
    away_team_zh: "巴塞罗那",
    competition: "Primera Division",
    competition_zh: "西甲",
    predicted_home_win: 0.41,
    predicted_draw: 0.28,
    predicted_away_win: 0.31,
    top1_score: "1:1",
    actual_home_goals: 1,
    actual_away_goals: 2,
    result: "away_win",
    prediction_correct: false,
    top3_hit: false,
    brier_score: 0.27,
  },
];
